### PR TITLE
Add versioning detail to readme, add version to deprecation warnings

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Add versioning plan to the readme and update deprecation warnings to give a version when the deprecation will be done.

### Documentation Change Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
Documentation change checklist:
- [ ] Any updated docstrings use the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).

### CODE REVIEW

**Comment by steven-murray** [comment]
https://pypi.org/project/deprecation/ could be helpful...

**Comment by bhazelton** [comment]
@steven-murray have you used that package? I've looked at it before but never actually used it in a project.

**Comment by steven-murray** [comment]
@bhazelton no I haven't. I really should though!

**Comment by bhazelton** [comment]
@jpober I think for now we'll use an issue on the repo which we can include in a milestone for the related release. But I am interested in the package @steven-murray pointed to and I think we should play with it a bit.

**Pull request merged**
