### PR TITLE
Better docs

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Improved documentation for SkyModel and for the generic `read` and `from_file` methods. These were meant to be included in #177 but were accidentally missed.
- update the RTD layout to put the attributes and methods on the same page (similar to recent changes in pyuvdata)
- Use file type specific section headings in the `read` and `from_file` docstrings.
- Pin the version of sphinx_rtd_theme that RTD uses in building the docs to restore bullets to our docs (see https://github.com/readthedocs/sphinx_rtd_theme/issues/1236).

Use the RTD CI link to see how this renders.

### Documentation Change Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
Documentation change checklist:
- [x] Any updated docstrings use the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).

### CODE REVIEW

**Comment by steven-murray** [comment]
Thanks @bhazelton  -- the rendering of the `read` and `from_file` methods looks good (though I still can't resist my feeling that we should use kwargs here haha). The only thing about the rendering that seems wrong to me is that under "Methods" the whole class docstring is put in, containing all the attributes (which are already listed in their own section above). This seems redundant and confusing.

**Comment by bhazelton** [comment]
Hmm, I see what you mean. I think the issue is that we actually have a pretty fully-featured `__init__` method on SkyModel and the list of items that seem redundant with the attributes are actually the parameters on the `__init__` method. There are some attributes that are not `__init__` parameters, though, so it's not exactly redundant. I'll re-work the top of the object docstring to try to make it better.

**Comment by bhazelton** [comment]
@steven-murray I've done some editing to try to help with the confusion between the attributes and the `__init__` parameters, along with some other minor fixes.

**Comment by bhazelton** [comment]
I think the issue is that there are multiple ways to build up an object. One is to pass a set of parameters to the `__init__` method, which will then do the calculations required. Another is to read in a file, which specifies everything. Yet another is to build up an object from scratch, in which case all the required parameters must be set. This is probably less common, but it is something some people may want/need to do and I want to be clear about that. I tried to explain that at the top of the document (before the attributes) and again in the object docstring, but I guess it's still not clear.

**Comment by steven-murray** [comment]
Ohhh, so you're saying that if you build it from scratch and set on "attribute" at a time, you need to specify eg. `Ncomponents` manually, and then check the object manually to make sure it's correct. 

OK, well, I think we *shouldn't* support that mode. I think it's too prone to error, and makes things more confusing. But if we *have* to support it, I guess we could make the docs here slightly more explicit?

**Review by jpober — APPROVED** [review]
I'm very happy with this, definitely more readable IMO and provides a template for adding new file types.

**Pull request merged**
