### PR TITLE
JOSS paper

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Preparation to submit to JOSS. The compiled paper draft can be seen as an artifact on the paper_draft workflow under Actions.

### Documentation Change Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
Documentation change checklist:
- [ ] Any updated docstrings use the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).

### CODE REVIEW

**Comment by bhazelton** [comment]
@aelanman We'd like your comments on this, you're listed as an author :)

**Review by aelanman — APPROVED** [review]
Looks good to me. Thanks for the co-author credit!

**Review by jpober — APPROVED** [review]
Looks great.  Any idea why checks are failing...?

**Comment by bhazelton** [comment]
Astropy 6.1 dropped on pypi (but interestingly not yet on conda) and some new warnings are being generated. I fixed a couple of things in our tests (no non-test code needed to be modified), but most of the warnings are coming from lunarsky, tracked in an issue here: https://github.com/aelanman/lunarsky/issues/27.

**Review by jpober — APPROVED** [review]
Still a lot of failures, alas.

**Comment by bhazelton** [comment]
Oh, yes. There's another transient issue I haven't run down where sometimes on mac builds in the install step setuptools_scm can't find git. Which makes no sense because the repo was cloned with git. This is occasionally seen in other repos too. For now I'll just re-run but long term we need to figure it out.

**Review by jpober — APPROVED** [review]
Warning tests are failing still, not just mac builds.

**Comment by bhazelton** [comment]
Right, the warning test failures are due to the new astropy warnings in lunar sky.

**Review by jpober — APPROVED** [review]
Still looks like the failing tests are blocking merging.  Do we want to override them?

**Comment by bhazelton** [comment]
I re-ran until only the warnings tests were failing, then merged.

**Pull request merged**
