### PR TITLE
Add a workflow to publish releases to pypi and testpypi

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Use a GitHub Action to publish releases on PyPI and to publish all pushes on TestPyPI to make sure things are working.

### Build/CI Change Checklist:

- [ ] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the readme to reflect this.
- [ ] If this is a new CI setup, I have added the associated badge to the readme

### CODE REVIEW

**Comment by bhazelton** [comment]
@steven-murray I updated this to use Paul's clever script for getting the local git hash into the testpypi deployment. Can you re-review? (I also fixed a problem I had with the testpypi access token, so the publishing is actually working).

**Comment by plaplant** [comment]
@steven-murray I think the idea of turning that script into a gist is a good one if it's going to be used by multiple repos. That way we only have to change it in one place in case anything comes up in the future. Since it's only needed for CI and not for local testing, I don't think grabbing it with wget is too onerous. I'm happy to make a gist if people find it useful.

**Comment by bhazelton** [comment]
sounds reasonable to me!

**Comment by plaplant** [comment]
Okay, I've made a gist here: https://gist.github.com/plaplant/0902f09e59166bac742bbd554f3cd2f9

I was able to download it with `wget https://gist.github.com/plaplant/0902f09e59166bac742bbd554f3cd2f9/raw/make_dev_version.sh`.

**Comment by bhazelton** [comment]
I updated this PR to use the gist.

**Pull request merged**
