### PR TITLE
Fix handling of hpx_order throughout, improve future equality warning

### LINKED ISSUE #140: What does this line do?
`check_acceptability` in a UVParameter only returns a tuple (True/False, message). Did we intend this line to catch if a user supplies and incorrect ordering scheme? It turns out that is actually done later by an astropy_healpix called linked below

https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/602cae56e4c24e5aa03948983f469d869a166015/pyradiosky/skymodel.py#L530

https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/602cae56e4c24e5aa03948983f469d869a166015/pyradiosky/skymodel.py#L544-L546

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Ensure that the `hpx_order` parameter is round tripped properly through the various conversion, read and write methods. Set it as a required parameter for healpix objects (this is backwards compatible because if it doesn't exist it is defaulted to 'ring' as it was being handled in the past).

Also improve the future equality warning which was very confusing and cleanup test warnings.
closes #140 

## Motivation and Context

We agreed in #134 to make hpx_order required for Healpix objects, but that was accidentally only implemented for the init function, not for the object. Since it wasn't required, we didn't notice that it wasn't being round tripped properly because when that happened it raised the future equality error which deceptively suggested the problem was to do with the frequency parameters rather than the hpx_order parameter.

In trying to clean up the test warnings, I fixed the future equality warning to clarify which parameters didn't match so that I could tell what was going on. That exposed this issue with hpx_order not being round tripped.

### Bug Fix Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible).
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
The pyuvsim external tests will be fixed my pyuvsim PR is merged (https://github.com/RadioAstronomySoftwareGroup/pyuvsim/pull/353)

**Review by mkolopanis — COMMENTED** [review]
Good catch on the healpix ordering. 

One thing I feel like I didn't see is a check with two healpix object with different ordering schemes to  ensure they are marked as not equal. Presumably they would be, but better safe than sorry?

Another comment I have is all the 
`Input ra and dec parameters are being used instead` actually comes from the `healpix_disk_new` fixture.  Not really a big deal, if I remember correctly #145 might be changing how the fixture works to handle the warnings too. We can probably iterate there more on this topic.

**Comment by bhazelton** [comment]
Good point about there not being an explicit test about ordering, I'll add it. I think I tried putting the filter on the fixture and it didn't work, but I can try again and if it doesn't work punt the problem to that PR.

**Comment by mkolopanis** [comment]
here's how I handled it in the other PR https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/25ff80c93cceb9aae1133d2648aa5c2e2e5d2de4/pyradiosky/tests/test_skymodel.py#L222-L236

**Comment by bhazelton** [comment]
I followed your pattern and could remove several of the filters. They are still needed in some tests, it seems that the skyh5 reader generates these warnings which seems less than ideal. I don't quite know the history of this warning though, so I'm not sure why the reader generates them.

**Review by mkolopanis — APPROVED** [review]
Thanks for adding that test!

**Pull request merged**
