### PR TITLE
Correct bug in unit string conversion

### LINKED ISSUE #137: Bug writing to skyh5
I am attempting to write a skyh5 file using the write_skyh5 function, and I'm encountering this error:
  File "/opt/anaconda3/lib/python3.7/site-packages/pyradiosky/skymodel.py", line 3505, in write_skyh5
    dgrp["stokes"].attrs["unit"] = self.stokes.unit.name
  File "/opt/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 560, in name
    "Can not get names from unnamed units. "
AttributeError: Can not get names from unnamed units. Perhaps you meant to_string()?

### PR DESCRIPTION
**Pull request by rlbyrne**
Closes #137 

### Bug Fix Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible).
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by mkolopanis** [comment]
while you're editing the write method, would you mind touching up this line too please? 
https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/602cae56e4c24e5aa03948983f469d869a166015/pyradiosky/skymodel.py#L3473

**Comment by mkolopanis** [comment]
Hm did we introduce this bug in another pr and not realize it? Seems like the failing tests on the minimum dependencies should be skipeed

**Comment by bhazelton** [comment]
Oops, yes. I added a test that needs to be skipped if astropy-healpix isn't present.

**Comment by bhazelton** [comment]
I changed this to use the units.name attribute when the stokes array is a Unit object (as opposed to a CompositeUnit object). But now I'm not sure that that's better than just calling `str` on the unit for both cases. @mkolopanis do you have an opinion?

**Comment by mkolopanis** [comment]
Yeah that's a good question, as some background for this discussion `str(unit)` just calls the `to_string()` method on the unit itself. And I would hope that string representation of units would be correctly formatted to then again initiate a unit from that string.

Personally I'm probably in favor of having as few lines as possible, but that requires hoping that units can handle everything correctly under the hood (which it seems is the case already).

**Comment by bhazelton** [comment]
Ok, I think I agree that the added complexity is not helpful. I'll take it back to Ruby's original one liner.

**Review by mkolopanis — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
