### PR TITLE
fix `at_frequencies` interpolation if there are NaNs in the stokes array

### LINKED ISSUE #164: Stokes is all NaN when interpolating GLEAM subbands using `at_frequencies`
This issue is on behalf of @piyanatk, based on an issue he raised in Slack. Quoting from Slack:
>I have a SkyModel object with GLEAM sources loaded in subband spectral type. I am trying to understand why when I evaluate the SkyModel with at_frequencies , the interpolation type must be set to “linear”. Otherwise, the method will return a new sky model with all NaNs in the stokes

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Fixed a bug where all the values in the output stokes array were NaN after calling `at_frequencies` on a subband object with some NaNs on a few sources in the stokes array.

Added the `nan_handling` keyword to the `at_frequencies` method to specify how NaNs in the stokes array are handled when interpolating subband spectral_type objects. These are handled per-component. Options are:
- "propagate": set all the output stokes to NaN if any input stokes are NaN
- "interp": interpolate using only the non-NaN values. If there are requested frequencies outside the non-NaN values for a source, set the stokes array at those frequencies to NaN.
- "clip": interpolate using only the non-NaN values. If there are requested frequencies outside the non-NaN values for a source, set the stokes array at those frequencies to the value at the nearest non-NaN frequency. (This is the default).

For all these choices, components with all NaN values in the input stokes array will have NaNs in the output stokes array. Also, if there are too few non-NaN values to do the chosen interpolation, a linear interpolation for that component will be done.

## Motivation and Context

fixes #164

### Bug Fix Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible).
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
@piyanatk can you see if this works as expected for you?

**Comment by bhazelton** [comment]
Thanks for the testing @piyanatk! I think I fixed all those issues now, can you try again?

**Comment by mkolopanis** [comment]
This looking good. It will be nice to have confirmation from @piyanatk though.

**Comment by piyanatk** [comment]
Thanks again @bhazelton. The new commits seem to fix all issues that I reported above.

However, I ran into another (maybe buggy) case that I do not understand. Let say I have a model with 2 components as follows.

| v Source / Frequency (MHz) > | 100 | 110 | 120 | 130 | 140 | 150 |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 1  | nan | 50 |  40  | nan | 20 | nan  |
| 2  | nan | 80 |  60  | 40 | nan | 20 |

Then, if I tried to evaluate the model at `[105, 115, 125, 135, 145]` MHz with either `nan_handling=clip` or `nan_handling=interp`, I get `
ValueError: A value in x_new is above the interpolation range.` But if I only evaluate at `[105, 115, 125, 135]` MHz, it works fine. `nan_handling="propagate"` work as expected.

**Comment by mkolopanis** [comment]
Given that component 1 has no information above 140MHz in your example. I'd say this is an expected outcome, but not totally useful error message for the user :thinking:

**Comment by bhazelton** [comment]
that's interesting. I thought I'd caught a case like that, I'll add a test and sort it out.

**Comment by bhazelton** [comment]
ah ha! I wasn't being careful enough when a source was missing both high and low frequency support. Just pushed a fix. Thanks for the careful testing @piyanatk !

**Review by mkolopanis — APPROVED** [review]
Good fix with the intersection. Looks good to me now! the docs are actually built I checked on rtd it's just not reporting back.

**Pull request merged**
