### PR TITLE
Better handling for lunar locations

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Change to an approach more similar to what we did in pyuvdata. This helps make it more clear which library is actually being used (astropy or lunarsky) for various operations. In this process I also identified and fixed some bugs related to properly rotating polarized sources for lunar locations.

Also require the newest version of lunarsky to get rid of astropy deprecation warnings.

### Bug Fix Checklist:

- [x] I have read the [contribution guide](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/.github/CONTRIBUTING.md).
- [x] My code follows the code style of this project.
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible).
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/blob/main/CHANGELOG.md).

### CODE REVIEW

**Comment by bhazelton** [comment]
@aelanman This is failing in a couple of tests because of a spicey error that I don't understand. Do you have any insight?

**Comment by aelanman** [comment]
@bhazelton I just see "Error:" when I look at the actions logs... what is the spiceypy error?

**Comment by bhazelton** [comment]
@aelanman I'm no longer seeing spiceypy errors, I'm not aware of anything that should have changed related to that, but I think we can let it go. I'd appreciate your review on this if/when you have time.

**Review by aelanman — APPROVED** [review]
Sorry for the slow response. This look good to me! Thank you for doing all this.

I think it's okay to merge this, but we should continue to keep an eye out for that spiceypy error. If it's something intermittent then it's a problem that should be addressed in `lunarsky`.

**Pull request merged**
